title: Michael Oluwaseun
logo: All in C:\Users\Cloud\Desktop
description: A data analyst with over 2 years of experience in data analytics, specialising in Structured Query Language (SQL) for data extraction, transformation, and data manipulation, Microsoft Excel for advanced reporting and modelling, and Power BI for business intelligence report. Experienced in cleaning, transforming, and analysing complex datasets to uncover trends, improve performance, and support data-driven decision-making across business functions. Passionate about turning raw data into clear, meaningful insights that drive strategic growth and operational efficiency.
#show_downloads: true
#google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
