title: Data Analyst
logo: /logo.png
description: |
  **Focus Areas**

  - Performance reporting and KPI tracking
  - Outcome and trend analysis
  - Risk pattern identification and evaluation
  - Operational activity and volume analysis
  - Insight generation to support strategic decision-making

#show_downloads: true
#google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
