title: Data Analyst
logo: /logo.png
description: |
  <strong>Focus Areas</strong>
  <ul>
    <li>SQL data extraction and transformation</li>
    <li>KPI reporting and performance analysis</li>
    <li>Trend and pattern analysis</li>
    <li>Dashboard development</li>
    <li>Insight generation for decision-making</li>
  </ul>

#show_downloads: true
#google_analytics:

remote_theme: pages-themes/minimal@v0.2.0

